######################################################################
### R for College Mathematics and Statistics
### Thomas J Pfaff
### Code for Chapter 2: Functions and Their Graphs
######################################################################

f=function(x){x^2*sin(x)}
f(3)

curve(f,-5,5)

#####

rectangle.area=function(l,w){l*w}
rectangle.area(4,6)

#####

area.triangle.sides=function(a,b,c){p=(a+b+c)/2;sqrt((p)*(p-a)*(p-b)*(p-c))}
area.triangle.sides(3,4,5)

##### A Piecewise-Defined Function #####

f.piecewise=function(x){ifelse(x<2,sin(x),x^2)}
f.piecewise(-pi/4)

curve(f.piecewise,-3,3,type="p",ylab="A Piecewise Function")
grid(NULL,NULL,col="black")

curve(f.piecewise,-3,3,type="n",ylab="A Piecewise Function")
grid(NULL,NULL,col="black")
curve(f.piecewise,-3,1.95,add=TRUE,lwd=2)
curve(f.piecewise,2,3,add=TRUE,lwd=2)
points(2,sin(2),pch=1,cex=1.5,lwd=2)
points(2,f.piecewise(2),pch=16,cex=1.5)

##### A Step Function #####

x=1:30
y=sapply(0:max(x),function(x)(1.10^x))
step=stepfun(x,y,right = TRUE)
plot(step,xlim=c(0,max(x)+1),ylim=c(0,20),lwd=2,xaxs="i",yaxs="i",
	verticals=FALSE,main="A Step Function")
abline(h=0:20,v=1:30,lty=3)

##### Polar Coordinates #####

library(pracma)
t=seq(0,2*pi, length=360)
f=function(t){5*sin(6*t)}
par(mar=c(1,1,2,1))
polar(t,f(t),grcol="gray20",bxcol="black",col="purple",lwd=2,
	main=expression(5*sin(6*theta)~ ~"and"~ ~2(5*sin(6*theta))/3))
polar(t,2*f(t)/3,col="purple",lty=2,lwd=2,add=TRUE)

##### Parametric Equations #####

x=function(t){sin(t)*(exp(cos(t))-2*cos(4*t)-(sin(t/12))^5)}
y=function(t){cos(t)*(exp(cos(t))-2*cos(4*t)-(sin(t/12))^5)}
Butterfly=function(t){return(c(x(t),y(t)))}
Butterfly(2*pi)

par(mar=c(1,1,1,1))
t.values=seq(0,12*pi, 0.001)
plot(x(t.values),y(t.values),type="l",col="purple",lwd=2,ann=FALSE,axes=FALSE)

##### Geometric Definition of a Parabola #####

library(rootSolve)
y.max=20
g=function(x){f=function(y){sqrt(x^2+(1-y)^2)-y} 
return(uniroot.all(f,c(0,y.max)))}
g(0)

h=Vectorize(g)
par(mar=c(5,3,3,2))
curve(h,-5,5, lwd=4, ylab="")
curve((x^2+1)/2,-5,5,add=TRUE,lty=3,lwd=4,col="gray70")

##### Functions that Return a Function #####

Reflect.origin=function(h){return(function(x){-h(-x)})}
f=function(x){x^5-3*x^2-3*x+2}
f(2)==Reflect.origin(f)(2)

par(mar=c(5.1,5.1,4.1,2.1))
curve(f,-2,2,ylim=c(-5,5),ylab=expression(f(x)==x^5-3*x^2-3*x+2),
	main="Graph of f(x) and its Reflection (in red) about the Origin")
curve(Reflect.origin(f)(x),-2,2,col="red",add=TRUE)
abline(v=0,h=0,lty=2)

E=function(a,b,c) {return(function(x){a*exp(b*x)+c})}
curve(E(2,1,10)(x),0,5,lwd=2,ylab=expression(2*e^(r*x)+10),
	main="r from 1 to 10")
for(r in 2:10){curve(E(2,r,10)(x),add=TRUE,lwd=2,col=rainbow(9)[r-1])}


##### Pythagorean Triples and a Checkerboard Plot #####

Euclid1=function(n,m){triple=numeric(3)
 triple[1]=m^2-n^2
 triple[2]=2*m*n
 triple[3]=m^2+n^2
 return(triple)}
Euclid1(2,3)

Euclid2=function(n,m){
 if (m > n){
 triple=numeric(3)
 triple[1]=m^2-n^2
 triple[2]=2*m*n
 triple[3]=m^2+n^2
 return(triple)}
 else {return("error")}}
Euclid2(3,2)

#####

n=c(1:1,1:2,1:3,1:4,1:5,1:6)
m=c(rep(2,1),rep(3,2),rep(4,3),rep(5,4),rep(6,5),rep(7,6))
A=matrix(c(n,m),ncol=2,byrow=FALSE)
A[1:5,]

Triples=mapply(Euclid1, A[,1], A[,2])
Triples[,1:5]

Two.Columns=cbind(rep(1:21,each=3),c(Triples))
Two.Columns[1:10,]

B=matrix(0,ncol=85,nrow=21)
B[Two.Columns]=1
B[1:2,1:10]

par(mar=c(3,3,4,2))
Title=expression(atop(paste("Pythagorean Triples Generated by ",m^2-n^2,", ",2*m*n, ",and",m^2+n^2,"."), 
	"The y-axis displays m with the values of n taken from 1 to m-1."))
image(t(B),axes=FALSE, col=c("white","black"),main=Title)
corners=par("usr")
abline(v=seq(corners[1],corners[2],len=86),h=seq(corners[3],corners[4],len=22))
axis(1,at=seq(0,1,length=85),label=FALSE)
start.axis=seq(0,1,length=85)[5]
axis(1,at=seq(start.axis,1,length=17),label=seq(5,85,by=5))
axis(2,at=seq(0,1,length=21),label=m,las=2)















