(function($) {
    $(document).ready(function() {
	
	$('#FuncAccum3_plot').scianimator({
	    'images': ['FuncAccum3_dir/FuncAccum3_plot1.png', 'FuncAccum3_dir/FuncAccum3_plot2.png', 'FuncAccum3_dir/FuncAccum3_plot3.png', 'FuncAccum3_dir/FuncAccum3_plot4.png', 'FuncAccum3_dir/FuncAccum3_plot5.png', 'FuncAccum3_dir/FuncAccum3_plot6.png', 'FuncAccum3_dir/FuncAccum3_plot7.png', 'FuncAccum3_dir/FuncAccum3_plot8.png', 'FuncAccum3_dir/FuncAccum3_plot9.png', 'FuncAccum3_dir/FuncAccum3_plot10.png', 'FuncAccum3_dir/FuncAccum3_plot11.png', 'FuncAccum3_dir/FuncAccum3_plot12.png', 'FuncAccum3_dir/FuncAccum3_plot13.png', 'FuncAccum3_dir/FuncAccum3_plot14.png', 'FuncAccum3_dir/FuncAccum3_plot15.png', 'FuncAccum3_dir/FuncAccum3_plot16.png', 'FuncAccum3_dir/FuncAccum3_plot17.png', 'FuncAccum3_dir/FuncAccum3_plot18.png', 'FuncAccum3_dir/FuncAccum3_plot19.png', 'FuncAccum3_dir/FuncAccum3_plot20.png', 'FuncAccum3_dir/FuncAccum3_plot21.png', 'FuncAccum3_dir/FuncAccum3_plot22.png', 'FuncAccum3_dir/FuncAccum3_plot23.png', 'FuncAccum3_dir/FuncAccum3_plot24.png', 'FuncAccum3_dir/FuncAccum3_plot25.png', 'FuncAccum3_dir/FuncAccum3_plot26.png', 'FuncAccum3_dir/FuncAccum3_plot27.png', 'FuncAccum3_dir/FuncAccum3_plot28.png', 'FuncAccum3_dir/FuncAccum3_plot29.png', 'FuncAccum3_dir/FuncAccum3_plot30.png', 'FuncAccum3_dir/FuncAccum3_plot31.png', 'FuncAccum3_dir/FuncAccum3_plot32.png', 'FuncAccum3_dir/FuncAccum3_plot33.png', 'FuncAccum3_dir/FuncAccum3_plot34.png', 'FuncAccum3_dir/FuncAccum3_plot35.png', 'FuncAccum3_dir/FuncAccum3_plot36.png', 'FuncAccum3_dir/FuncAccum3_plot37.png', 'FuncAccum3_dir/FuncAccum3_plot38.png', 'FuncAccum3_dir/FuncAccum3_plot39.png', 'FuncAccum3_dir/FuncAccum3_plot40.png', 'FuncAccum3_dir/FuncAccum3_plot41.png', 'FuncAccum3_dir/FuncAccum3_plot42.png', 'FuncAccum3_dir/FuncAccum3_plot43.png', 'FuncAccum3_dir/FuncAccum3_plot44.png', 'FuncAccum3_dir/FuncAccum3_plot45.png', 'FuncAccum3_dir/FuncAccum3_plot46.png', 'FuncAccum3_dir/FuncAccum3_plot47.png', 'FuncAccum3_dir/FuncAccum3_plot48.png', 'FuncAccum3_dir/FuncAccum3_plot49.png', 'FuncAccum3_dir/FuncAccum3_plot50.png', 'FuncAccum3_dir/FuncAccum3_plot51.png', 'FuncAccum3_dir/FuncAccum3_plot52.png', 'FuncAccum3_dir/FuncAccum3_plot53.png', 'FuncAccum3_dir/FuncAccum3_plot54.png', 'FuncAccum3_dir/FuncAccum3_plot55.png', 'FuncAccum3_dir/FuncAccum3_plot56.png', 'FuncAccum3_dir/FuncAccum3_plot57.png', 'FuncAccum3_dir/FuncAccum3_plot58.png', 'FuncAccum3_dir/FuncAccum3_plot59.png', 'FuncAccum3_dir/FuncAccum3_plot60.png', 'FuncAccum3_dir/FuncAccum3_plot61.png', 'FuncAccum3_dir/FuncAccum3_plot62.png', 'FuncAccum3_dir/FuncAccum3_plot63.png', 'FuncAccum3_dir/FuncAccum3_plot64.png'],
	    'width': 800,
	    'delay': 200,
	    'loopMode': 'loop',
 'controls': ['first', 'previous', 'play', 'next', 'last', 'loop', 'speed']
	});
    });
})(jQuery);
