(function($) {
    $(document).ready(function() {
	
	$('#FuncDeriv_plot').scianimator({
	    'images': ['FuncDeriv_dir/FuncDeriv_plot1.png', 'FuncDeriv_dir/FuncDeriv_plot2.png', 'FuncDeriv_dir/FuncDeriv_plot3.png', 'FuncDeriv_dir/FuncDeriv_plot4.png', 'FuncDeriv_dir/FuncDeriv_plot5.png', 'FuncDeriv_dir/FuncDeriv_plot6.png', 'FuncDeriv_dir/FuncDeriv_plot7.png', 'FuncDeriv_dir/FuncDeriv_plot8.png', 'FuncDeriv_dir/FuncDeriv_plot9.png', 'FuncDeriv_dir/FuncDeriv_plot10.png', 'FuncDeriv_dir/FuncDeriv_plot11.png', 'FuncDeriv_dir/FuncDeriv_plot12.png', 'FuncDeriv_dir/FuncDeriv_plot13.png', 'FuncDeriv_dir/FuncDeriv_plot14.png', 'FuncDeriv_dir/FuncDeriv_plot15.png', 'FuncDeriv_dir/FuncDeriv_plot16.png', 'FuncDeriv_dir/FuncDeriv_plot17.png', 'FuncDeriv_dir/FuncDeriv_plot18.png', 'FuncDeriv_dir/FuncDeriv_plot19.png', 'FuncDeriv_dir/FuncDeriv_plot20.png', 'FuncDeriv_dir/FuncDeriv_plot21.png', 'FuncDeriv_dir/FuncDeriv_plot22.png', 'FuncDeriv_dir/FuncDeriv_plot23.png', 'FuncDeriv_dir/FuncDeriv_plot24.png', 'FuncDeriv_dir/FuncDeriv_plot25.png', 'FuncDeriv_dir/FuncDeriv_plot26.png', 'FuncDeriv_dir/FuncDeriv_plot27.png', 'FuncDeriv_dir/FuncDeriv_plot28.png', 'FuncDeriv_dir/FuncDeriv_plot29.png', 'FuncDeriv_dir/FuncDeriv_plot30.png', 'FuncDeriv_dir/FuncDeriv_plot31.png', 'FuncDeriv_dir/FuncDeriv_plot32.png', 'FuncDeriv_dir/FuncDeriv_plot33.png', 'FuncDeriv_dir/FuncDeriv_plot34.png', 'FuncDeriv_dir/FuncDeriv_plot35.png', 'FuncDeriv_dir/FuncDeriv_plot36.png', 'FuncDeriv_dir/FuncDeriv_plot37.png', 'FuncDeriv_dir/FuncDeriv_plot38.png', 'FuncDeriv_dir/FuncDeriv_plot39.png', 'FuncDeriv_dir/FuncDeriv_plot40.png', 'FuncDeriv_dir/FuncDeriv_plot41.png', 'FuncDeriv_dir/FuncDeriv_plot42.png', 'FuncDeriv_dir/FuncDeriv_plot43.png', 'FuncDeriv_dir/FuncDeriv_plot44.png', 'FuncDeriv_dir/FuncDeriv_plot45.png', 'FuncDeriv_dir/FuncDeriv_plot46.png', 'FuncDeriv_dir/FuncDeriv_plot47.png', 'FuncDeriv_dir/FuncDeriv_plot48.png', 'FuncDeriv_dir/FuncDeriv_plot49.png', 'FuncDeriv_dir/FuncDeriv_plot50.png', 'FuncDeriv_dir/FuncDeriv_plot51.png', 'FuncDeriv_dir/FuncDeriv_plot52.png', 'FuncDeriv_dir/FuncDeriv_plot53.png', 'FuncDeriv_dir/FuncDeriv_plot54.png', 'FuncDeriv_dir/FuncDeriv_plot55.png', 'FuncDeriv_dir/FuncDeriv_plot56.png', 'FuncDeriv_dir/FuncDeriv_plot57.png', 'FuncDeriv_dir/FuncDeriv_plot58.png', 'FuncDeriv_dir/FuncDeriv_plot59.png', 'FuncDeriv_dir/FuncDeriv_plot60.png', 'FuncDeriv_dir/FuncDeriv_plot61.png'],
	    'width': 800,
	    'delay': 200,
	    'loopMode': 'loop',
 'controls': ['first', 'previous', 'play', 'next', 'last', 'loop', 'speed']
	});
    });
})(jQuery);
